### ISSUE TITLE
Conflict between Qigsaw and Fabric gradle plugin. 

### ISSUE THREAD

**Issue by aj-chou** [iqiyi/Qigsaw#10]
Hi Qigsaw team,

There is a circular dependency issue between **Qigsaw gradle plugin** and gradle plugin of **[Fabric Crashlytics](https://docs.fabric.io/android/crashlytics)** crash reporting framework.

When executing release build type
`./gradlew qigsawAssembleMyFlavorRelease `

The error log is like:

    Circular dependency between the following tasks:
        :app:bundleMyFlavorReleaseClasses
        +--- :app:compileMyFlavorReleaseJavaWithJavac
        |    +--- :app:compileMyFlavorReleaseKotlin
        |    |    \--- :app:processMyFlavorReleaseResources
        |    |         \--- :app:mergeMyFlavorReleaseResources
        |    |              \--- :app:fabricGenerateResourcesMyFlavorRelease
        |    |                   \--- :app:mergeMyFlavorReleaseAssets
        |    |                        \--- :app:qigsawAssembleMyFlavorRelease
        |    |                             \--- :myDynamicFeature:assembleMyFlavorRelease
        |    |                                  +--- :myDynamicFeature:compileMyFlavorReleaseSources
        |    |                                  |    \--- :myDynamicFeature:compileMyFlavorReleaseJavaWithJavac
        |    |                                  |         +--- :app:bundleMyFlavorReleaseClasses (*)
        |    |                                  |         +--- :myDynamicFeature:javaPreCompileMyFlavorRelease
        |    |                                  |         |    \--- :app:bundleMyFlavorReleaseClasses (*)
        |    |                                  |         \--- :myDynamicFeature:processMyFlavorReleaseResources
        |    |                                  |              \--- :app:processMyFlavorReleaseResources (*)
        |    |                                  +--- :myDynamicFeature:lintVitalMyFlavorRelease
        |    |                                  |    \--- :myDynamicFeature:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                  \--- :myDynamicFeature:packageMyFlavorRelease
        |    |                                       +--- :app:transformDexWithDexSplitterForMyFlavorRelease
        |    |                                       |    +--- :app:transformClassesAndResourcesWithProguardForMyFlavorRelease
        |    |                                       |    |    +--- :app:mergeMyFlavorReleaseAaptProguardFiles
        |    |                                       |    |    |    +--- :app:processMyFlavorReleaseResources (*)
        |    |                                       |    |    |    \--- :myDynamicFeature:processMyFlavorReleaseResources (*)
        |    |                                       |    |    +--- :app:transformClassesWithFirebasePerformancePluginForMyFlavorRelease
        |    |                                       |    |    |    \--- :app:transformClassesWithCreateComponentInfoTransformForMyFlavorRelease
        |    |                                       |    |    |         +--- :app:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                       |    |    |         \--- :app:compileMyFlavorReleaseKotlin (*)
        |    |                                       |    |    +--- :app:transformResourcesWithMergeJavaResForMyFlavorRelease
        |    |                                       |    |    |    +--- :app:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                       |    |    |    +--- :app:compileMyFlavorReleaseKotlin (*)
        |    |                                       |    |    |    \--- :myDynamicFeature:transformResourcesWithMergeJavaResForMyFlavorRelease
        |    |                                       |    |    |         \--- :myDynamicFeature:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                       |    |    \--- :myDynamicFeature:transformClassesWithMergeClassesForMyFlavorRelease
        |    |                                       |    |         \--- :myDynamicFeature:transformClassesWithSplitComponentTransformForMyFlavorRelease
        |    |                                       |    |              \--- :myDynamicFeature:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                       |    +--- :app:transformClassesWithMergeClassesForMyFlavorRelease
        |    |                                       |    |    \--- :app:transformClassesWithFirebasePerformancePluginForMyFlavorRelease (*)
        |    |                                       |    +--- :app:transformDexArchiveWithDexMergerForMyFlavorRelease
        |    |                                       |    |    \--- :app:transformClassesWithDexBuilderForMyFlavorRelease
        |    |                                       |    |         \--- :app:transformClassesAndResourcesWithProguardForMyFlavorRelease (*)
        |    |                                       |    \--- :myDynamicFeature:transformClassesWithMergeClassesForMyFlavorRelease (*)
        |    |                                       +--- :myDynamicFeature:compileMyFlavorReleaseJavaWithJavac (*)
        |    |                                       +--- :myDynamicFeature:processMyFlavorReleaseResources (*)
        |    |                                       +--- :myDynamicFeature:transformDexArchiveWithDexMergerForMyFlavorRelease
        |    |                                       |    \--- :myDynamicFeature:transformClassesWithDexBuilderForMyFlavorRelease
        |    |                                       |         +--- :app:bundleMyFlavorReleaseClasses (*)
        |    |                                       |         \--- :myDynamicFeature:transformClassesWithSplitComponentTransformForMyFlavorRelease (*)
        |    |                                       \--- :myDynamicFeature:transformResourcesWithMergeJavaResForMyFlavorRelease (*)
        |    +--- :app:generateMyFlavorReleaseSources
        |    |    \--- :app:fabricGenerateResourcesMyFlavorRelease (*)
        |    +--- :app:javaPreCompileMyFlavorRelease
        |    |    \--- :app:compileMyFlavorReleaseKotlin (*)
        |    \--- :app:processMyFlavorReleaseResources (*)
        \--- :app:compileMyFlavorReleaseKotlin (*)

The project contains simple "myDynamicFeature" dynamic feature module and simple product flavor "MyFlavor".

For debug build type it's fine since the fabricGenerateResources gradle task of Fabric would not be added to the dependsOn list. But not the case for the release build.

Please help check if Qigsaw framework can work with Fabric Crashlytics.

THX.

**Comment by kissonchan** [comment]
Sorry for the late replay, I would check it.

**Comment by huopochuan** [comment]
three chinese?

**Comment by kissonchan** [comment]
fixed. See more [support flavor extension](https://github.com/iqiyi/Qigsaw/commit/9a5a6574a3ee0982463491526ae58e7e3ee2de67)
