### ISSUE TITLE
不支持ARouter

### ISSUE THREAD

**Issue by MarkMjw** [iqiyi/Qigsaw#12]
项目中用了ARouter，集成Qigsaw之后module之间无法跳转，应该是ARouter不支持app bundle，不知道有没有其他解决办法。

**Comment by kissonchan** [comment]
这个需要ARouter团队支持了，插件升级适配。

**Comment by MarkMjw** [comment]
> > 这个需要ARouter团队支持了，插件升级适配  贵团队组件化跳转通信是自己写的框架支持app bundle吗

放弃ARouter了，这个[Component](https://github.com/xiaojinzi123/Component)支持App Bundle
