### ISSUE TITLE
com.android.tools.build:gradle:3.6.2 报错

### ISSUE THREAD

**Issue by DonaldDu** [iqiyi/Qigsaw#14]
> Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'property(interface org.gradle.api.file.Directory, property(interface org.gradle.api.file.Directory, fixed(class org.gradle.api.internal.file.DefaultFilePropertyFactory$FixedDirectory, C:\datas\QigsawTest\app\build\outputs\apk\debug)))' with class 'org.gradle.api.internal.file.DefaultFilePropertyFactory$DefaultDirectoryVar' to class 'java.io.File'

**Comment by kissonchan** [comment]
暂未适配，敬请期待

**Comment by kissonchan** [comment]
已经fixed。等待发布新版本
