### ISSUE TITLE
有个疑问？插件模块apk更新，为什么不涉及为通过url请求判断是否更新，如果是然后下载apk,进行加载。而是通过Qigsaw#updateSplits的方式？

### ISSUE THREAD

**Issue by huopochuan** [iqiyi/Qigsaw#15]
有个疑问？插件模块apk更新，为什么不涉及为通过url请求判断是否更新，如果是然后下载apk,进行加载。而是通过Qigsaw#updateSplits的方式？

**Comment by kissonchan** [comment]
简化操作吧，通过URL更新就涉及后台的一些更新策略了。比如爱奇艺提供类似的云服务就会有此种功能了。
