### ISSUE TITLE
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException:  

### ISSUE THREAD

**Issue by Hosseinyzr** [iqiyi/Qigsaw#18]
Hi,
when I ad dependencies and want to sync project ,  I face this error:

Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find builder.jar (com.android.tools.build:builder:3.4.2).

**Comment by kissonchan** [comment]
> Hi,
> when I ad dependencies and want to sync project , I face this error:
> 
> Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find builder.jar (com.android.tools.build:builder:3.4.2).

what's your gradle api version in gradle-wrapper.properties file?
