### ISSUE TITLE
有几个疑问

### ISSUE THREAD

**Issue by spysoos** [iqiyi/Qigsaw#19]
1 不使用tinker的情况下，加载插件的数量就是固定的？
2 主App 远程下载完插件到本地后，安装插件过程是不是会弹出安装界面让用户操作？
3 看到sample里 各个feature 都引用了 :app模块，是不是可这么理解：公共库可以放到 app模块内,插件在编译时会把app里的代码也一并编译到插件内生成插件apk? 如果不是，请问，各个featrue都使用到的公共库应该怎么引入？
4 请问这个库目前能在Android 10上正常运行吗？

谢谢

**Comment by kissonchan** [comment]
1. 插件数固定，用tinker也不一定支持。
2. 不会
3. 可以，具体用法与app bundle一致，请看官方文档
4.android 10、11都正常

**Comment by spysoos** [comment]
3Q
