### ISSUE TITLE
应该是libPath吧

### ISSUE THREAD

**Issue by changjiashuai** [iqiyi/Qigsaw#2]
https://github.com/iqiyi/Qigsaw/blob/e8079217b1b413245228503a701d77b36be78f19/qigsaw-android/splitloader/src/main/java/com/iqiyi/android/qigsaw/core/splitload/SplitCompatLibraryLoader.java#L69

**Comment by kissonchan** [comment]
这段逻辑可以删掉，Qigsaw只支持V14及以上
