### ISSUE TITLE
每次更新 app 版本，所有 feature 库都需要重新下载安装，体验太不好了吧

### ISSUE THREAD

**Issue by kuangzhongwen** [iqiyi/Qigsaw#24]
即时 feature 库代码没有改动，也需要重新下载安装

**Comment by huopochuan** [comment]
确实

**Comment by kissonchan** [comment]
因为插件和宿主一起打包混淆，即使没插件没改动，打出来的插件APK也会变化。

**Comment by kuangzhongwen** [comment]
如果使用统一的 mapping 文件或者 feature 库单独维护混淆呢

**Comment by kuangzhongwen** [comment]
如果使用统一的 mapping 文件或者 feature 库单独维护混淆呢

**Comment by kissonchan** [comment]
> 如果使用统一的 mapping 文件或者 feature 库单独维护混淆呢

这样开发维护成本就会剧增，还有一些系统兼容性问题，也要考虑，目前还不考虑。
