### ISSUE TITLE
从技术角度看，有点意思，实际应用角度意义不大

### ISSUE THREAD

**Issue by NanCoGu** [iqiyi/Qigsaw#3]
从携程 360  腾讯 阿里开源的一些插件化 热加载等等框架，工程开发过程中还是有点复杂度的，小项目用不上，大项目直接拆分多个产品App，加上展示类功能H5化，基本能减少大部分的APK大小。
感觉国内开源都是把快淘汰的技术放出来，纯技术讨论用。哈哈哈

**Comment by kissonchan** [comment]
一般来说插件化框架 在小项目中使用有成本。不过Qigsaw屏蔽了一些流程，让小团队也能很快使用动态下载插件。这也是Qigsaw的优势之一，详情可以见wiki啊。哈哈

**Comment by pk00789o** [comment]
把apk放到自己的服务器上，对谷歌来说是红线吧，国内可以这样玩玩。

**Comment by kissonchan** [comment]
> 把apk放到自己的服务器上，对谷歌来说是红线吧，国内可以这样玩玩。
做Qigsaw的目的就是给国内用的，国外直接切到Android App Bundle

**Comment by hf529270451** [comment]
用Qigsaw  可以理解为内部使用AAB的api 和谷歌未来的android版本升级同步吗？不会因为禁止隐藏api就不能用了吧
