### ISSUE TITLE
项目后面需要插件化，看了几个插件化框架比较后，决定使用此框架，现在有几个问题需要请教下

### ISSUE THREAD

**Issue by pzl0708** [iqiyi/Qigsaw#33]
1. 插件上传自己服务器是在此方法中实现，并且返回上传地址？
![das](https://user-images.githubusercontent.com/45899342/96952466-7d95b780-1521-11eb-9cb9-1160302f9f53.jpg)
2. 生成的插件信息JSON文件是需要手动在后台服务器配置吗

**Comment by kissonchan** [comment]
1. 对的，可以使用你司统一上传CDN服务。
2. 这个可以根据你们需要来处理。

**Comment by pzl0708** [comment]
好的，谢谢

**Comment by NBXXF** [comment]
这个方法 怎么不执行？要怎样才执行呢
