### ISSUE TITLE
Qigsaw Error: MultiDex or R8 task is missing

### ISSUE THREAD

**Issue by whc1998** [iqiyi/Qigsaw#37]
按照接入流程文档配置编译出现以下问题，还麻烦看看是什么问题。
Qigsaw Error: MultiDex or R8 task is missing

**Comment by JackyAnn** [comment]
@whc1998  要开启 MultiDex

**Comment by whc1998** [comment]
> @whc1998 要开启 MultiDex

这个是打开了的，在gradle和application中都已经打开

**Comment by kissonchan** [comment]
> 按照接入流程文档配置编译出现以下问题，还麻烦看看是什么问题。
> Qigsaw Error: MultiDex or R8 task is missing

请使用 1.4.1-hotfix02 版本
