### ISSUE TITLE
qigsaw-android-sample compile error:

### ISSUE THREAD

**Issue by mengshu** [iqiyi/Qigsaw#9]
Ubuntu 18.04
branch:master
last commit: 12936b4814d6fa08f57a310029fa4aa59edb9f41

$cd /Qigsaw/qigsaw-android-sample
$./gradlew qigsawAssembleDebug

> Task :app:validateSigningDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:validateSigningDebug'.
> Keystore file '/home/XXXX/workspace/Qigsaw/qigsaw-android-sample/keystore/debug.jks' not found for signing config 'debug'.

the keystore file search fail?

I print the value:
in qigsaw-android-sample,:
project is ":app"
project:rootProject is "qigsaw-android-sample" not "qigsaw"

I think there is solution:
change:
 storeFile new File(project.rootProject.projectDir.absolutePath + "/keystore/release.jks")
to
 storeFile new File("../keystore/release.jks")

and 

change:
 storeFile new File(project.rootProject.projectDir.absolutePath + "/keystore/debug.jks")
to
 storeFile new File("../keystore/debug.jks")

is ok.

**Comment by kissonchan** [comment]
Copy keystore to sample project
